# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi, I'm JK
logo: /assets/logo.png
email: iamknightbat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where i chill.
url: "https://knightbat.github.io"

navigation_header:
  Home: /
  Contact Me: /contact

navigation_footer:
  Created by Me: https://github.com/knightbat


social_links:
  Twitter: https://twitter.com/iamknightbat
  LinkedIn: https://www.linkedin.com/in/knightbat
  Google+: https://plus.google.com/+JayakrishnanM
  GitHub: https://github.com/knightbat
sass:
  style: compressed # Style compression
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji
exclude:
  - README.md
  - LICENSE
